[package]
name = "engine"
version = "0.1.0"
authors = ["Kyle Burke <kyle.n.burke@gmail.com>"]
edition = '2018'

[dependencies]
ash = "0.31.0"
freetype = "0.7.0"
glfw = { version = "0.40.0", features = ["vulkan"] }